language: "fr"
title: "Échantillons"
subtitle: "Exemples de contenu pour le livre électrique"
description: "Exemples de contenu pour le livre électrique"
products:
  print-pdf:
    files:
      - "00-03-title-page"
      - "00-04-copyright-page"
      - "00-05-contents-page"
      - "01-00-text"
      - "01-01-plain-text-1"
      - "01-01-plain-text-2"
      - "01-01-plain-text-3"
      - "02-00-images"
      - "02-01-plain-images"
      - "03-02-maths"
      - "10-02-dynamic-index"
    toc:
      - label: "Texte"
        children:
          - label: "Texte brut"
            file: "01-01-plain-text-1"
            id: "texte-brut"
            children:
              - label: "I"
                file: "01-01-plain-text-1"
                id: "i"
              - label: "II"
                file: "01-01-plain-text-2"
                id: "ii"
              - label: "III"
                file: "01-01-plain-text-3"
                id: "iii"
      - label: "Images"
        children:
          - file: "02-01-plain-images"
            label: "Images simples"
            id: "images-simples"
      - label: "Mathématiques"
        file: "03-02-maths"
      - label: "Index dynamique"
        file: "10-02-dynamic-index"
  web:
    files: # Required for translations to activate language-selector
      - "00-00-cover"
      - "00-03-title-page"
      - "00-04-copyright-page"
      - "00-05-contents-page"
      - "01-00-text"
      - "01-01-plain-text-1"
      - "01-01-plain-text-2"
      - "01-01-plain-text-3"
      - "02-00-images"
      - "02-01-plain-images"
      - "03-02-maths"
      - "10-02-dynamic-index"
    nav:
      - file: "00-00-cover"
        label: "Couverture"
      - file: "00-03-title-page"
        label: "Titre"
      - file: "00-04-copyright-page"
        label: "Droits"
      - file: "00-05-contents-page"
        label: "Table des matières"
      - label: "Texte"
        children:
          - label: "Texte brut"
            file: "01-01-plain-text-1"
            id: "texte-brut"
            children:
              - label: "I"
                file: "01-01-plain-text-1"
                id: "i"
              - label: "II"
                file: "01-01-plain-text-2"
                id: "ii"
              - label: "III"
                file: "01-01-plain-text-3"
                id: "iii"
      - label: "Images"
        children:
          - file: "02-01-plain-images"
            label: "Images simples"
      - label: "Mathématiques"
        file: "03-02-maths"
      - label: "Index dynamique"
        file: "10-02-dynamic-index"
  screen-pdf:
    files:
      - "00-00-cover"
      - "00-03-title-page"
      - "00-04-copyright-page"
      - "00-05-contents-page"
      - "01-00-text"
      - "01-01-plain-text-1"
      - "01-01-plain-text-2"
      - "01-01-plain-text-3"
      - "02-00-images"
      - "02-01-plain-images"
      - "03-02-maths"
      - "10-02-dynamic-index"
  epub:
    files: # add a value to any file to set any of the guide types listed in http://www.idpf.org/epub/20/spec/OPF_2.0.1_draft.htm#Section2.6
      - "00-00-cover": "cover"
      - "00-03-title-page": "title-page"
      - "00-04-copyright-page": "copyright-page"
      - "00-05-contents-page": "toc"
      - "01-00-text": "text"
      - "01-01-plain-text-1"
      - "01-01-plain-text-2"
      - "01-01-plain-text-3"
      - "02-00-images"
      - "02-01-plain-images"
      - "03-02-maths"
      - "10-02-dynamic-index"
  app:
    files: # Required for translations to activate language-selector
      - "00-00-cover"
      - "00-03-title-page"
      - "00-04-copyright-page"
      - "00-05-contents-page"
      - "01-00-text"
      - "01-01-plain-text-1"
      - "01-01-plain-text-2"
      - "01-01-plain-text-3"
      - "02-00-images"
      - "02-01-plain-images"
      - "03-02-maths"
      - "10-02-dynamic-index"