# Set site.output == "screen-pdf"
output: "screen-pdf"
# Set site.image-set == "images/screen-pdf"
image-set: "images/screen-pdf"
# Turn off documentation
collections:
  docs:
    output: false
  api:
    output: false
exclude:
  # The usual excludes from _config.yml
  - run.js
  - Gemfile
  - Gemfile.lock
  - README*
  - LICENSE*
  - CHANGELOG*
  - node_modules
  - eslint.json
  - gulpfile.js
  - package.json
  - package-lock.json
  - CNAME
  - .sass-cache

  # Included as-is in other files, no need to process
  - /assets/js/annotation.js
  - /assets/js/baseline-grid.js
  - /assets/js/polyfills.js
  - /assets/js/utilities.js
  - /assets/js/settings.js
  - /assets/js/locales.js
  - /assets/js/setup.js
  - /assets/js/mark-parents.js
  - /assets/js/mark.min.js
  - /assets/js/redact.js
  - /assets/js/search-store.js
  - /assets/js/search-terms.js
  - /assets/js/nav.js
  - /assets/js/videos.js
  - /assets/js/mcqs.js
  - /assets/js/select-list.js
  - /assets/js/tables.js
  - /assets/js/footnote-popups.js
  - /assets/js/show-hide.js
  - /assets/js/elasticlunr.min.js
  - /assets/js/elasticlunr-setup.js
  - /assets/js/svg-management.js
  - /assets/js/svg-inject.min.js
  - /assets/js/lazyload.js
  - /assets/js/accordion.js
  - /assets/js/heading-titles.js
  - /assets/js/rotate.js
  - /assets/js/footnotes.js
  - /assets/js/shift-elements.js
  - /assets/js/page-reference.js
  - /assets/js/bookmarks.js

  # Exclude files we don't need for screen-pdf
  - _api
  - /about.md
  - /contact.md
  - /deploy.sh
  - /fr
  - /index.md
  - /netlify.toml
  - /search.md
  - /sitemap.xml
  - /test.sh
  - /assets/styles/app*
  - /assets/styles/web*
  - /assets/js/accordion.js
  - /assets/js/annotation.js
  - /assets/js/elasticlunr-setup.js
  - /assets/js/elasticlunr.min.js
  - /assets/js/mark.min.js
  - /assets/js/mcqs.js
  - /assets/js/nav.js
  - /assets/js/render-search-index.js
  - /assets/js/search-index.js
  - /assets/js/search-results.js
  - /assets/js/search-store.js
  - /assets/js/search-terms.js
  - /assets/js/videos.js
  - /*/package.opf
  - /*/toc.ncx
  - /*/styles/print-pdf.scss
  - /*/styles/web.scss
  - /*/styles/epub.scss
  - /*/styles/app.scss
  - /*/images/print-pdf
  - /*/images/web
  - /*/images/epub
  - /*/images/app

# Temporarily exclude these and keep_files them below
# for faster builds where you don't need to refresh these.
  # - /assets/fonts
  # - /book/fonts
  # - /book/styles
  # - /samples/00-00-cover
  # - /samples/00-01-halftitle-page
  # - /samples/00-02-previous-publications-page
  # - /samples/00-03-title-page
  # - /samples/00-04-copyright-page
  # - /samples/00-05-contents-page
  # - /samples/00-06-dedication-page
  # - /samples/00-07-epigraph-page
  # - /samples/00-08-frontispiece-page
  # - /samples/00-09-frontmatter
  # - /samples/01-00-text
  # - /samples/01-01-plain-text
  # - /samples/01-02-headings
  # - /samples/01-03-quotes
  # - /samples/01-04-lists
  # - /samples/01-05-tables
  # - /samples/01-06-boxes
  # - /samples/01-07-notes
  # - /samples/01-08-dividers
  # - /samples/01-09-poetry
  # - /samples/01-10-questions
  # - /samples/02-00-images
  # - /samples/02-01-plain-images
  # - /samples/02-02-figures
  # - /samples/03-00-code-and-maths
  # - /samples/03-01-code
  # - /samples/03-02-maths
  # - /samples/04-00-interactivity
  # - /samples/04-01-links-buttons
  # - /samples/04-02-video
  # - /samples/04-03-audio
  # - /samples/04-04-iframes
  # - /samples/04-05-slides
  # - /samples/10-00-indexes
  # - /samples/10-01-traditional-index
  # - /samples/10-02-dynamic-index
  # - /samples/question-01

# Populate the keep_files list for temporary faster builds
# or to keep previously generated files for other formats.
keep_files:
  # - assets/fonts
  # - book/fonts
  # - book/styles
