# Live website build config
# Use this to override defaults in _config.yml

# This is the live build
build: live

# URLs
canonical-url: "https://example.com"
baseurl: "/example"

# Turn off docs.
# Setting output: false actually doesn't work,
# see https://github.com/jekyll/jekyll/issues/7504
# so we also exclude the _docs below.
collections:
  docs:
    output: false

# Exclude list
exclude:
  # Build tools
  - README.md
  - LICENSE
  - run.js
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - node_modules
  - gulpfile.js
  - eslint.json
  - CHANGELOG.md
  - /*/images/source

  # Included as-is in other files, no need to process
  - /assets/js/annotation.js
  - /assets/js/baseline-grid.js
  - /assets/js/polyfills.js
  - /assets/js/utilities.js
  - /assets/js/settings.js
  - /assets/js/locales.js
  - /assets/js/setup.js
  - /assets/js/mark-parents.js
  - /assets/js/mark.min.js
  - /assets/js/redact.js
  - /assets/js/search-store.js
  - /assets/js/search-terms.js
  - /assets/js/nav.js
  - /assets/js/videos.js
  - /assets/js/mcqs.js
  - /assets/js/select-list.js
  - /assets/js/tables.js
  - /assets/js/footnote-popups.js
  - /assets/js/show-hide.js
  - /assets/js/elasticlunr.min.js
  - /assets/js/elasticlunr-setup.js
  - /assets/js/svg-management.js
  - /assets/js/svg-inject.min.js
  - /assets/js/lazyload.js
  - /assets/js/accordion.js
  - /assets/js/heading-titles.js
  - /assets/js/rotate.js
  - /assets/js/footnotes.js
  - /assets/js/shift-elements.js
  - /assets/js/page-reference.js
  - /assets/js/bookmarks.js

  # Collections that must not render
  - _docs

  # Colour profiles for conversions
  - /assets/profiles

  # Scripts we don't need for web output
  - /assets/js/heading-titles.js

  # Book files we don't need for web
  - /*/images/print-pdf
  - /*/images/screen-pdf
  - /*/images/epub
  - /*/images/app
  - /*/styles/epub*
  - /*/styles/print-pdf*
  - /*/styles/screen-pdf*
  - /*/styles/app*
  - /*/package.opf
  - /*/toc.ncx

  # Exclude web images only if you keep_files them below
  # - /*/images/web

  # Exclude translations not ready for prime time
  # - /*/fr

# Keep list. Adjust for faster output,
# if you know what you're doing.
keep_files:
  # - book/images/print-pdf
  # - book/images/screen-pdf
  # - book/images/web
  # - book/images/epub
  # - book/fonts
  # - book/styles
  # - book/01.html
  # - book/02.html
